<?php

namespace Database\Seeders;

use App\Models\Cliente;
use Illuminate\Database\Seeder;

class ClienteSeeder extends Seeder
{
    public function run(): void
    {
        $clientes = [
            // Originais
            [
                'nome'        => 'João Silva Santos',
                'telefone'    => '(11) 99999-1234',
                'email'       => 'joao.silva@email.com',
                'endereco'    => 'Rua das Flores, 123',
                'cidade'      => 'São Paulo',
                'estado'      => 'SP',
                'cep'         => '01310-100',
                'documento'   => '123.456.789-00',
                'observacoes' => null,
            ],
            [
                'nome'        => 'Maria Aparecida Oliveira',
                'telefone'    => '(21) 98888-5678',
                'email'       => 'maria.oliveira@email.com',
                'endereco'    => 'Av. Copacabana, 456',
                'cidade'      => 'Rio de Janeiro',
                'estado'      => 'RJ',
                'cep'         => '22070-011',
                'documento'   => '987.654.321-00',
                'observacoes' => 'Cliente frequente, sempre traz iPhone.',
            ],
            [
                'nome'        => 'Pedro Henrique Costa',
                'telefone'    => '(31) 97777-9012',
                'email'       => 'pedro.costa@email.com',
                'endereco'    => 'Rua da Bahia, 789',
                'cidade'      => 'Belo Horizonte',
                'estado'      => 'MG',
                'cep'         => '30160-011',
                'documento'   => '456.789.123-00',
                'observacoes' => null,
            ],
            [
                'nome'        => 'Ana Claudia Ferreira',
                'telefone'    => '(41) 96666-3456',
                'email'       => 'ana.ferreira@email.com',
                'endereco'    => 'Rua XV de Novembro, 321',
                'cidade'      => 'Curitiba',
                'estado'      => 'PR',
                'cep'         => '80020-310',
                'documento'   => '321.654.987-00',
                'observacoes' => 'Prefere ser contatada por WhatsApp.',
            ],
            [
                'nome'        => 'Carlos Roberto Souza',
                'telefone'    => '(51) 95555-7890',
                'email'       => 'carlos.souza@email.com',
                'endereco'    => 'Av. Ipiranga, 654',
                'cidade'      => 'Porto Alegre',
                'estado'      => 'RS',
                'cep'         => '90160-093',
                'documento'   => '789.123.456-00',
                'observacoes' => null,
            ],
            [
                'nome'        => 'Fernanda Rocha Almeida',
                'telefone'    => '(61) 94444-1234',
                'email'       => 'fernanda.rocha@email.com',
                'endereco'    => 'SQN 312, Bloco A',
                'cidade'      => 'Brasília',
                'estado'      => 'DF',
                'cep'         => '70766-010',
                'documento'   => '654.321.789-00',
                'observacoes' => null,
            ],
            [
                'nome'        => 'Ricardo Mendes Barbosa',
                'telefone'    => '(11) 93333-4567',
                'email'       => 'ricardo.mendes@email.com',
                'endereco'    => 'Rua Augusta, 987',
                'cidade'      => 'São Paulo',
                'estado'      => 'SP',
                'cep'         => '01304-000',
                'documento'   => '111.222.333-00',
                'observacoes' => 'Empresário, traz equipamentos da empresa.',
            ],
            [
                'nome'        => 'Juliana Martins Pereira',
                'telefone'    => '(11) 92222-5678',
                'email'       => 'juliana.martins@email.com',
                'endereco'    => 'Rua Oscar Freire, 147',
                'cidade'      => 'São Paulo',
                'estado'      => 'SP',
                'cep'         => '01426-001',
                'documento'   => '444.555.666-00',
                'observacoes' => null,
            ],
            [
                'nome'        => 'Marcos Paulo Rodrigues',
                'telefone'    => '(19) 91111-6789',
                'email'       => 'marcos.rodrigues@email.com',
                'endereco'    => 'Av. Brasil, 258',
                'cidade'      => 'Campinas',
                'estado'      => 'SP',
                'cep'         => '13013-001',
                'documento'   => '777.888.999-00',
                'observacoes' => null,
            ],
            [
                'nome'        => 'Luciana Carvalho Lima',
                'telefone'    => '(11) 90000-7890',
                'email'       => 'luciana.lima@email.com',
                'endereco'    => 'Rua Consolação, 369',
                'cidade'      => 'São Paulo',
                'estado'      => 'SP',
                'cep'         => '01302-000',
                'documento'   => '000.111.222-33',
                'observacoes' => 'Leva sempre notebook para manutenção.',
            ],

            // Novos clientes
            [
                'nome'        => 'Alexandre Torres Melo',
                'telefone'    => '(11) 98100-0001',
                'email'       => 'alexandre.torres@email.com',
                'endereco'    => 'Rua Vergueiro, 500',
                'cidade'      => 'São Paulo',
                'estado'      => 'SP',
                'cep'         => '01504-000',
                'documento'   => '100.200.300-01',
                'observacoes' => null,
            ],
            [
                'nome'        => 'Beatriz Lemos Tavares',
                'telefone'    => '(11) 98100-0002',
                'email'       => 'beatriz.lemos@email.com',
                'endereco'    => 'Alameda Santos, 200',
                'cidade'      => 'São Paulo',
                'estado'      => 'SP',
                'cep'         => '01419-000',
                'documento'   => '100.200.300-02',
                'observacoes' => 'Sempre paga no cartão.',
            ],
            [
                'nome'        => 'Cláudio Pires Nogueira',
                'telefone'    => '(11) 98100-0003',
                'email'       => 'claudio.pires@email.com',
                'endereco'    => 'Rua Teodoro Sampaio, 800',
                'cidade'      => 'São Paulo',
                'estado'      => 'SP',
                'cep'         => '05406-050',
                'documento'   => '100.200.300-03',
                'observacoes' => null,
            ],
            [
                'nome'        => 'Daniela Freitas Assis',
                'telefone'    => '(19) 98100-0004',
                'email'       => 'daniela.freitas@email.com',
                'endereco'    => 'Rua das Castanheiras, 40',
                'cidade'      => 'Campinas',
                'estado'      => 'SP',
                'cep'         => '13082-005',
                'documento'   => '100.200.300-04',
                'observacoes' => 'Traz filhos para reparar celulares.',
            ],
            [
                'nome'        => 'Eduardo Bittencourt Cruz',
                'telefone'    => '(11) 98100-0005',
                'email'       => 'eduardo.bittencourt@email.com',
                'endereco'    => 'Av. Paulista, 1000',
                'cidade'      => 'São Paulo',
                'estado'      => 'SP',
                'cep'         => '01310-100',
                'documento'   => '100.200.300-05',
                'observacoes' => 'Executivo, prefere atendimento prioritário.',
            ],
            [
                'nome'        => 'Flávia Gonçalves Dias',
                'telefone'    => '(41) 98100-0006',
                'email'       => 'flavia.goncalves@email.com',
                'endereco'    => 'Rua Marechal Floriano, 150',
                'cidade'      => 'Curitiba',
                'estado'      => 'PR',
                'cep'         => '80230-000',
                'documento'   => '100.200.300-06',
                'observacoes' => null,
            ],
            [
                'nome'        => 'Gabriel Matos Vieira',
                'telefone'    => '(11) 98100-0007',
                'email'       => 'gabriel.matos@email.com',
                'endereco'    => 'Rua da Mooca, 220',
                'cidade'      => 'São Paulo',
                'estado'      => 'SP',
                'cep'         => '03103-000',
                'documento'   => '100.200.300-07',
                'observacoes' => 'Jovem, usa muito o celular para trabalho.',
            ],
            [
                'nome'        => 'Helena Ribeiro Campos',
                'telefone'    => '(21) 98100-0008',
                'email'       => 'helena.ribeiro@email.com',
                'endereco'    => 'Rua Voluntários da Pátria, 88',
                'cidade'      => 'Rio de Janeiro',
                'estado'      => 'RJ',
                'cep'         => '22270-010',
                'documento'   => '100.200.300-08',
                'observacoes' => null,
            ],
            [
                'nome'        => 'Igor Santana Leal',
                'telefone'    => '(85) 98100-0009',
                'email'       => 'igor.santana@email.com',
                'endereco'    => 'Av. Beira-Mar, 300',
                'cidade'      => 'Fortaleza',
                'estado'      => 'CE',
                'cep'         => '60165-121',
                'documento'   => '100.200.300-09',
                'observacoes' => null,
            ],
            [
                'nome'        => 'Joana Drumond Paixão',
                'telefone'    => '(31) 98100-0010',
                'email'       => 'joana.drumond@email.com',
                'endereco'    => 'Rua Guajajaras, 50',
                'cidade'      => 'Belo Horizonte',
                'estado'      => 'MG',
                'cep'         => '30180-100',
                'documento'   => '100.200.300-10',
                'observacoes' => 'Professora, traz notebook da escola.',
            ],
            [
                'nome'        => 'Kaique Borba Feitosa',
                'telefone'    => '(81) 98100-0011',
                'email'       => 'kaique.borba@email.com',
                'endereco'    => 'Av. Boa Viagem, 600',
                'cidade'      => 'Recife',
                'estado'      => 'PE',
                'cep'         => '51011-000',
                'documento'   => '100.200.300-11',
                'observacoes' => null,
            ],
            [
                'nome'        => 'Larissa Paiva Monteiro',
                'telefone'    => '(71) 98100-0012',
                'email'       => 'larissa.paiva@email.com',
                'endereco'    => 'Av. Oceânica, 120',
                'cidade'      => 'Salvador',
                'estado'      => 'BA',
                'cep'         => '40170-010',
                'documento'   => '100.200.300-12',
                'observacoes' => null,
            ],
            [
                'nome'        => 'Matheus Dutra Aquino',
                'telefone'    => '(11) 98100-0013',
                'email'       => 'matheus.dutra@email.com',
                'endereco'    => 'Rua Tutóia, 900',
                'cidade'      => 'São Paulo',
                'estado'      => 'SP',
                'cep'         => '04007-001',
                'documento'   => '100.200.300-13',
                'observacoes' => 'Técnico de outra área, às vezes faz troca de peças.',
            ],
            [
                'nome'        => 'Natália Sousa Carmo',
                'telefone'    => '(62) 98100-0014',
                'email'       => 'natalia.sousa@email.com',
                'endereco'    => 'Rua 84, 45',
                'cidade'      => 'Goiânia',
                'estado'      => 'GO',
                'cep'         => '74093-140',
                'documento'   => '100.200.300-14',
                'observacoes' => null,
            ],
            [
                'nome'        => 'Otávio Maciel Ramos',
                'telefone'    => '(92) 98100-0015',
                'email'       => 'otavio.maciel@email.com',
                'endereco'    => 'Av. Eduardo Ribeiro, 520',
                'cidade'      => 'Manaus',
                'estado'      => 'AM',
                'cep'         => '69010-001',
                'documento'   => '100.200.300-15',
                'observacoes' => null,
            ],
            [
                'nome'        => 'Patricia Vasconcelos Braga',
                'telefone'    => '(11) 98100-0016',
                'email'       => 'patricia.vasconcelos@email.com',
                'endereco'    => 'Rua Pamplona, 700',
                'cidade'      => 'São Paulo',
                'estado'      => 'SP',
                'cep'         => '01405-001',
                'documento'   => '100.200.300-16',
                'observacoes' => 'Advogada, tem dois celulares para reparar.',
            ],
            [
                'nome'        => 'Rodrigo Furtado Magno',
                'telefone'    => '(51) 98100-0017',
                'email'       => 'rodrigo.furtado@email.com',
                'endereco'    => 'Av. Carlos Gomes, 300',
                'cidade'      => 'Porto Alegre',
                'estado'      => 'RS',
                'cep'         => '90480-003',
                'documento'   => '100.200.300-17',
                'observacoes' => null,
            ],
            [
                'nome'        => 'Simone Cavalcante Porto',
                'telefone'    => '(83) 98100-0018',
                'email'       => 'simone.cavalcante@email.com',
                'endereco'    => 'Rua Duque de Caxias, 400',
                'cidade'      => 'João Pessoa',
                'estado'      => 'PB',
                'cep'         => '58013-001',
                'documento'   => '100.200.300-18',
                'observacoes' => null,
            ],
            [
                'nome'        => 'Thiago Neto Azevedo',
                'telefone'    => '(11) 98100-0019',
                'email'       => 'thiago.neto@email.com',
                'endereco'    => 'Rua Treze de Maio, 1500',
                'cidade'      => 'São Paulo',
                'estado'      => 'SP',
                'cep'         => '01327-000',
                'documento'   => '100.200.300-19',
                'observacoes' => 'Traz sempre dois aparelhos juntos.',
            ],
            [
                'nome'        => 'Ursula Lima Novaes',
                'telefone'    => '(11) 98100-0020',
                'email'       => 'ursula.lima@email.com',
                'endereco'    => 'Rua Bela Cintra, 200',
                'cidade'      => 'São Paulo',
                'estado'      => 'SP',
                'cep'         => '01415-000',
                'documento'   => '100.200.300-20',
                'observacoes' => null,
            ],
            [
                'nome'        => 'Victor Hugo Saraiva',
                'telefone'    => '(21) 98100-0021',
                'email'       => 'victor.saraiva@email.com',
                'endereco'    => 'Rua Barata Ribeiro, 80',
                'cidade'      => 'Rio de Janeiro',
                'estado'      => 'RJ',
                'cep'         => '22011-000',
                'documento'   => '100.200.300-21',
                'observacoes' => null,
            ],
            [
                'nome'        => 'Wanda Fonseca Estrela',
                'telefone'    => '(31) 98100-0022',
                'email'       => 'wanda.fonseca@email.com',
                'endereco'    => 'Rua Espírito Santo, 100',
                'cidade'      => 'Belo Horizonte',
                'estado'      => 'MG',
                'cep'         => '30160-030',
                'documento'   => '100.200.300-22',
                'observacoes' => 'Idosa, precisa de atendimento com paciência.',
            ],
            [
                'nome'        => 'Xisto Ramos Queirós',
                'telefone'    => '(79) 98100-0023',
                'email'       => 'xisto.ramos@email.com',
                'endereco'    => 'Av. Ivo do Prado, 75',
                'cidade'      => 'Aracaju',
                'estado'      => 'SE',
                'cep'         => '49010-070',
                'documento'   => '100.200.300-23',
                'observacoes' => null,
            ],
            [
                'nome'        => 'Yasmin Corrêa Belém',
                'telefone'    => '(91) 98100-0024',
                'email'       => 'yasmin.correa@email.com',
                'endereco'    => 'Travessa Benjamim Constant, 12',
                'cidade'      => 'Belém',
                'estado'      => 'PA',
                'cep'         => '66035-065',
                'documento'   => '100.200.300-24',
                'observacoes' => null,
            ],
            [
                'nome'        => 'Zara Mendonça Fontes',
                'telefone'    => '(11) 98100-0025',
                'email'       => 'zara.mendonca@email.com',
                'endereco'    => 'Rua Haddock Lobo, 1200',
                'cidade'      => 'São Paulo',
                'estado'      => 'SP',
                'cep'         => '01414-003',
                'documento'   => '100.200.300-25',
                'observacoes' => 'Prefere orçamento por e-mail.',
            ],
            [
                'nome'        => 'Antônio Carlos Rezende',
                'telefone'    => '(11) 98100-0026',
                'email'       => 'antonio.rezende@email.com',
                'endereco'    => 'Rua Itapeva, 350',
                'cidade'      => 'São Paulo',
                'estado'      => 'SP',
                'cep'         => '01332-000',
                'documento'   => '100.200.300-26',
                'observacoes' => null,
            ],
            [
                'nome'        => 'Breno Castilho Araújo',
                'telefone'    => '(61) 98100-0027',
                'email'       => 'breno.castilho@email.com',
                'endereco'    => 'SHS Quadra 06, Bloco C',
                'cidade'      => 'Brasília',
                'estado'      => 'DF',
                'cep'         => '70316-000',
                'documento'   => '100.200.300-27',
                'observacoes' => 'Servidor público, fatura no final do mês.',
            ],
            [
                'nome'        => 'Camila Siqueira Brandão',
                'telefone'    => '(11) 98100-0028',
                'email'       => 'camila.siqueira@email.com',
                'endereco'    => 'Rua Frei Caneca, 50',
                'cidade'      => 'São Paulo',
                'estado'      => 'SP',
                'cep'         => '01307-001',
                'documento'   => '100.200.300-28',
                'observacoes' => null,
            ],
            [
                'nome'        => 'Diego Albuquerque Leite',
                'telefone'    => '(81) 98100-0029',
                'email'       => 'diego.albuquerque@email.com',
                'endereco'    => 'Av. Caxangá, 3500',
                'cidade'      => 'Recife',
                'estado'      => 'PE',
                'cep'         => '52020-010',
                'documento'   => '100.200.300-29',
                'observacoes' => null,
            ],
            [
                'nome'        => 'Elisa Wanderley Guedes',
                'telefone'    => '(11) 98100-0030',
                'email'       => 'elisa.wanderley@email.com',
                'endereco'    => 'Rua Estados Unidos, 700',
                'cidade'      => 'São Paulo',
                'estado'      => 'SP',
                'cep'         => '01427-000',
                'documento'   => '100.200.300-30',
                'observacoes' => 'Trouxe recomendação de amigo. Primeira visita.',
            ],
            [
                'nome'        => 'Fábio Nascimento Duarte',
                'telefone'    => '(47) 98100-0031',
                'email'       => 'fabio.nascimento@email.com',
                'endereco'    => 'Rua XV de Novembro, 800',
                'cidade'      => 'Joinville',
                'estado'      => 'SC',
                'cep'         => '89201-100',
                'documento'   => '100.200.300-31',
                'observacoes' => null,
            ],
            [
                'nome'        => 'Giovanna Pessoa Uchoa',
                'telefone'    => '(85) 98100-0032',
                'email'       => 'giovanna.pessoa@email.com',
                'endereco'    => 'Rua Nogueira Acioli, 120',
                'cidade'      => 'Fortaleza',
                'estado'      => 'CE',
                'cep'         => '60110-140',
                'documento'   => '100.200.300-32',
                'observacoes' => null,
            ],
            [
                'nome'        => 'Humberto Bastos Véras',
                'telefone'    => '(11) 98100-0033',
                'email'       => 'humberto.bastos@email.com',
                'endereco'    => 'Av. Rebouças, 1800',
                'cidade'      => 'São Paulo',
                'estado'      => 'SP',
                'cep'         => '05402-300',
                'documento'   => '100.200.300-33',
                'observacoes' => 'Tem plano empresarial para 3 aparelhos.',
            ],
            [
                'nome'        => 'Irene Prado Lacerda',
                'telefone'    => '(11) 98100-0034',
                'email'       => 'irene.prado@email.com',
                'endereco'    => 'Rua Butantã, 400',
                'cidade'      => 'São Paulo',
                'estado'      => 'SP',
                'cep'         => '05228-000',
                'documento'   => '100.200.300-34',
                'observacoes' => null,
            ],
            [
                'nome'        => 'Jean Carlos Valente',
                'telefone'    => '(43) 98100-0035',
                'email'       => 'jean.valente@email.com',
                'endereco'    => 'Rua Professor João Cândido, 200',
                'cidade'      => 'Londrina',
                'estado'      => 'PR',
                'cep'         => '86010-001',
                'documento'   => '100.200.300-35',
                'observacoes' => null,
            ],
            [
                'nome'        => 'Keila Nunes Barreto',
                'telefone'    => '(71) 98100-0036',
                'email'       => 'keila.nunes@email.com',
                'endereco'    => 'Av. ACM, 2500',
                'cidade'      => 'Salvador',
                'estado'      => 'BA',
                'cep'         => '41950-000',
                'documento'   => '100.200.300-36',
                'observacoes' => null,
            ],
            [
                'nome'        => 'Leandro Marinho Severo',
                'telefone'    => '(11) 98100-0037',
                'email'       => 'leandro.marinho@email.com',
                'endereco'    => 'Rua João Moura, 100',
                'cidade'      => 'São Paulo',
                'estado'      => 'SP',
                'cep'         => '05412-000',
                'documento'   => '100.200.300-37',
                'observacoes' => 'Motoboy, sempre com celular danificado por queda.',
            ],
            [
                'nome'        => 'Mirella Castro Barros',
                'telefone'    => '(21) 98100-0038',
                'email'       => 'mirella.castro@email.com',
                'endereco'    => 'Rua Conde de Bonfim, 450',
                'cidade'      => 'Rio de Janeiro',
                'estado'      => 'RJ',
                'cep'         => '20520-054',
                'documento'   => '100.200.300-38',
                'observacoes' => null,
            ],
            [
                'nome'        => 'Nilton Pedrosa Lyra',
                'telefone'    => '(82) 98100-0039',
                'email'       => 'nilton.pedrosa@email.com',
                'endereco'    => 'Av. Fernandes Lima, 700',
                'cidade'      => 'Maceió',
                'estado'      => 'AL',
                'cep'         => '57050-000',
                'documento'   => '100.200.300-39',
                'observacoes' => null,
            ],
            [
                'nome'        => 'Olivia Teixeira Maia',
                'telefone'    => '(11) 98100-0040',
                'email'       => 'olivia.teixeira@email.com',
                'endereco'    => 'Rua Aspicuelta, 90',
                'cidade'      => 'São Paulo',
                'estado'      => 'SP',
                'cep'         => '05433-010',
                'documento'   => '100.200.300-40',
                'observacoes' => null,
            ],
        ];

        foreach ($clientes as $cliente) {
            Cliente::updateOrCreate(
                ['email' => $cliente['email']],
                $cliente
            );
        }
    }
}