<?php

namespace Database\Seeders;

use App\Models\Estoque;
use Illuminate\Database\Seeder;

class EstoqueSeeder extends Seeder
{
    public function run(): void
    {
        $itens = [
            // ── Telas ──────────────────────────────────────────
            [
                'nome'              => 'Tela iPhone 13 Original',
                'descricao'         => 'Display LCD original Apple para iPhone 13. Com digitalizador.',
                'sku'               => 'IPH13-TELA-ORI',
                'quantidade'        => 0,
                'quantidade_minima' => 2,
                'preco_custo'       => 180.00,
                'preco_venda'       => 350.00,
            ],
            [
                'nome'              => 'Tela iPhone 14 Original',
                'descricao'         => 'Display OLED original Apple para iPhone 14. Com digitalizador.',
                'sku'               => 'IPH14-TELA-ORI',
                'quantidade'        => 2,
                'quantidade_minima' => 2,
                'preco_custo'       => 250.00,
                'preco_venda'       => 480.00,
            ],
            [
                'nome'              => 'Tela iPhone 12 Original',
                'descricao'         => 'Display OLED original Apple para iPhone 12.',
                'sku'               => 'IPH12-TELA-ORI',
                'quantidade'        => 3,
                'quantidade_minima' => 2,
                'preco_custo'       => 160.00,
                'preco_venda'       => 320.00,
            ],
            [
                'nome'              => 'Tela iPhone 11 Original',
                'descricao'         => 'Display LCD original Apple para iPhone 11.',
                'sku'               => 'IPH11-TELA-ORI',
                'quantidade'        => 4,
                'quantidade_minima' => 2,
                'preco_custo'       => 130.00,
                'preco_venda'       => 280.00,
            ],
            [
                'nome'              => 'Tela Samsung Galaxy A54',
                'descricao'         => 'Display AMOLED para Samsung Galaxy A54. Com moldura.',
                'sku'               => 'SAM-A54-TELA',
                'quantidade'        => 4,
                'quantidade_minima' => 2,
                'preco_custo'       => 120.00,
                'preco_venda'       => 280.00,
            ],
            [
                'nome'              => 'Tela Samsung Galaxy S23',
                'descricao'         => 'Display AMOLED para Samsung Galaxy S23.',
                'sku'               => 'SAM-S23-TELA',
                'quantidade'        => 2,
                'quantidade_minima' => 1,
                'preco_custo'       => 200.00,
                'preco_venda'       => 420.00,
            ],
            [
                'nome'              => 'Tela Samsung Galaxy A34',
                'descricao'         => 'Display Super AMOLED para Samsung Galaxy A34.',
                'sku'               => 'SAM-A34-TELA',
                'quantidade'        => 5,
                'quantidade_minima' => 2,
                'preco_custo'       => 100.00,
                'preco_venda'       => 240.00,
            ],
            [
                'nome'              => 'Tela Motorola Moto G84',
                'descricao'         => 'Display POLED para Moto G84. Original.',
                'sku'               => 'MOT-G84-TELA',
                'quantidade'        => 3,
                'quantidade_minima' => 2,
                'preco_custo'       => 95.00,
                'preco_venda'       => 220.00,
            ],
            [
                'nome'              => 'Tela Motorola Moto G73',
                'descricao'         => 'Display IPS LCD para Moto G73.',
                'sku'               => 'MOT-G73-TELA',
                'quantidade'        => 3,
                'quantidade_minima' => 2,
                'preco_custo'       => 85.00,
                'preco_venda'       => 200.00,
            ],
            [
                'nome'              => 'Tela Xiaomi Redmi Note 12',
                'descricao'         => 'Display AMOLED para Xiaomi Redmi Note 12.',
                'sku'               => 'XIA-RN12-TELA',
                'quantidade'        => 4,
                'quantidade_minima' => 2,
                'preco_custo'       => 90.00,
                'preco_venda'       => 210.00,
            ],
            [
                'nome'              => 'Tela Notebook Dell 15.6"',
                'descricao'         => 'Tela LCD 15.6 polegadas Full HD para notebooks Dell.',
                'sku'               => 'DELL-TELA-156',
                'quantidade'        => 1,
                'quantidade_minima' => 1,
                'preco_custo'       => 210.00,
                'preco_venda'       => 420.00,
            ],
            [
                'nome'              => 'Tela Notebook HP 14"',
                'descricao'         => 'Tela LCD 14 polegadas HD para notebooks HP.',
                'sku'               => 'HP-TELA-14',
                'quantidade'        => 2,
                'quantidade_minima' => 1,
                'preco_custo'       => 180.00,
                'preco_venda'       => 380.00,
            ],
            [
                'nome'              => 'Tela Notebook Lenovo IdeaPad 15"',
                'descricao'         => 'Tela LCD 15.6" FHD para Lenovo IdeaPad série 3.',
                'sku'               => 'LEN-TELA-15',
                'quantidade'        => 1,
                'quantidade_minima' => 1,
                'preco_custo'       => 195.00,
                'preco_venda'       => 400.00,
            ],

            // ── Baterias ───────────────────────────────────────
            [
                'nome'              => 'Bateria iPhone 13',
                'descricao'         => 'Bateria de reposição para iPhone 13. 3227 mAh.',
                'sku'               => 'IPH13-BAT',
                'quantidade'        => 5,
                'quantidade_minima' => 3,
                'preco_custo'       => 80.00,
                'preco_venda'       => 150.00,
            ],
            [
                'nome'              => 'Bateria iPhone 14',
                'descricao'         => 'Bateria de reposição para iPhone 14. 3279 mAh.',
                'sku'               => 'IPH14-BAT',
                'quantidade'        => 3,
                'quantidade_minima' => 2,
                'preco_custo'       => 100.00,
                'preco_venda'       => 190.00,
            ],
            [
                'nome'              => 'Bateria iPhone 12',
                'descricao'         => 'Bateria de reposição para iPhone 12. 2815 mAh.',
                'sku'               => 'IPH12-BAT',
                'quantidade'        => 6,
                'quantidade_minima' => 3,
                'preco_custo'       => 70.00,
                'preco_venda'       => 140.00,
            ],
            [
                'nome'              => 'Bateria Samsung Galaxy A54',
                'descricao'         => 'Bateria original para Samsung Galaxy A54. 5000 mAh.',
                'sku'               => 'SAM-A54-BAT',
                'quantidade'        => 1,
                'quantidade_minima' => 3,
                'preco_custo'       => 45.00,
                'preco_venda'       => 120.00,
            ],
            [
                'nome'              => 'Bateria Samsung Galaxy S23',
                'descricao'         => 'Bateria para Samsung Galaxy S23. 3900 mAh.',
                'sku'               => 'SAM-S23-BAT',
                'quantidade'        => 4,
                'quantidade_minima' => 2,
                'preco_custo'       => 60.00,
                'preco_venda'       => 140.00,
            ],
            [
                'nome'              => 'Bateria Motorola Moto G84',
                'descricao'         => 'Bateria para Moto G84. 5000 mAh.',
                'sku'               => 'MOT-G84-BAT',
                'quantidade'        => 3,
                'quantidade_minima' => 2,
                'preco_custo'       => 40.00,
                'preco_venda'       => 110.00,
            ],
            [
                'nome'              => 'Bateria Xiaomi Redmi Note 12',
                'descricao'         => 'Bateria para Xiaomi Redmi Note 12. 5000 mAh.',
                'sku'               => 'XIA-RN12-BAT',
                'quantidade'        => 5,
                'quantidade_minima' => 2,
                'preco_custo'       => 38.00,
                'preco_venda'       => 105.00,
            ],
            [
                'nome'              => 'Bateria Notebook Dell 11.1V',
                'descricao'         => 'Bateria para notebooks Dell Inspiron série 3000/5000.',
                'sku'               => 'DELL-BAT-111',
                'quantidade'        => 2,
                'quantidade_minima' => 1,
                'preco_custo'       => 130.00,
                'preco_venda'       => 280.00,
            ],
            [
                'nome'              => 'Bateria Notebook HP 10.8V',
                'descricao'         => 'Bateria para notebooks HP série 240/250 G7/G8.',
                'sku'               => 'HP-BAT-108',
                'quantidade'        => 2,
                'quantidade_minima' => 1,
                'preco_custo'       => 120.00,
                'preco_venda'       => 260.00,
            ],
            [
                'nome'              => 'Bateria Notebook Lenovo 10.8V',
                'descricao'         => 'Bateria para notebooks Lenovo IdeaPad série 3/5.',
                'sku'               => 'LEN-BAT-108',
                'quantidade'        => 1,
                'quantidade_minima' => 1,
                'preco_custo'       => 115.00,
                'preco_venda'       => 250.00,
            ],

            // ── Conectores e cabos ────────────────────────────
            [
                'nome'              => 'Conector de Carga USB-C Universal',
                'descricao'         => 'Conector de carga USB-C compatível com diversos modelos Android.',
                'sku'               => 'CON-USBC-UNI',
                'quantidade'        => 15,
                'quantidade_minima' => 5,
                'preco_custo'       => 12.00,
                'preco_venda'       => 35.00,
            ],
            [
                'nome'              => 'Conector de Carga Lightning (iPhone)',
                'descricao'         => 'Conector Lightning para iPhones 5 ao 14.',
                'sku'               => 'CON-LIGHT-UNI',
                'quantidade'        => 12,
                'quantidade_minima' => 5,
                'preco_custo'       => 18.00,
                'preco_venda'       => 45.00,
            ],
            [
                'nome'              => 'Cabo Flex Samsung (modelo variado)',
                'descricao'         => 'Cabo flat/flex para reparo de placas Samsung.',
                'sku'               => 'SAM-FLEX-001',
                'quantidade'        => 8,
                'quantidade_minima' => 5,
                'preco_custo'       => 25.00,
                'preco_venda'       => 60.00,
            ],
            [
                'nome'              => 'Cabo Flex Motorola (modelo variado)',
                'descricao'         => 'Cabo flat/flex para reparos de placas Motorola.',
                'sku'               => 'MOT-FLEX-001',
                'quantidade'        => 6,
                'quantidade_minima' => 3,
                'preco_custo'       => 22.00,
                'preco_venda'       => 55.00,
            ],
            [
                'nome'              => 'Cabo SATA para HD/SSD',
                'descricao'         => 'Cabo SATA III para conexão de HD e SSD em notebooks.',
                'sku'               => 'CAB-SATA-001',
                'quantidade'        => 20,
                'quantidade_minima' => 5,
                'preco_custo'       => 8.00,
                'preco_venda'       => 25.00,
            ],

            // ── Componentes eletrônicos ───────────────────────
            [
                'nome'              => 'Capacitor Eletrolítico 1000µF 25V',
                'descricao'         => 'Capacitor eletrolítico 1000µF 25V. Para reparo de fontes e TVs.',
                'sku'               => 'CAP-1000UF-25V',
                'quantidade'        => 50,
                'quantidade_minima' => 10,
                'preco_custo'       => 0.50,
                'preco_venda'       => 3.00,
            ],
            [
                'nome'              => 'Capacitor Eletrolítico 470µF 16V',
                'descricao'         => 'Capacitor eletrolítico 470µF 16V de uso geral.',
                'sku'               => 'CAP-470UF-16V',
                'quantidade'        => 60,
                'quantidade_minima' => 15,
                'preco_custo'       => 0.40,
                'preco_venda'       => 2.50,
            ],
            [
                'nome'              => 'Transistor BC548',
                'descricao'         => 'Transistor NPN BC548 de uso geral.',
                'sku'               => 'TRANS-BC548',
                'quantidade'        => 100,
                'quantidade_minima' => 20,
                'preco_custo'       => 0.30,
                'preco_venda'       => 2.00,
            ],
            [
                'nome'              => 'Transistor BC558',
                'descricao'         => 'Transistor PNP BC558 de uso geral.',
                'sku'               => 'TRANS-BC558',
                'quantidade'        => 80,
                'quantidade_minima' => 20,
                'preco_custo'       => 0.30,
                'preco_venda'       => 2.00,
            ],
            [
                'nome'              => 'Diodo 1N4007',
                'descricao'         => 'Diodo retificador 1N4007 1A 1000V.',
                'sku'               => 'DIO-1N4007',
                'quantidade'        => 200,
                'quantidade_minima' => 30,
                'preco_custo'       => 0.20,
                'preco_venda'       => 1.50,
            ],
            [
                'nome'              => 'Fusível 5A 250V',
                'descricao'         => 'Fusível de vidro 5A 250V. Para fontes e eletrodomésticos.',
                'sku'               => 'FUS-5A-250V',
                'quantidade'        => 30,
                'quantidade_minima' => 10,
                'preco_custo'       => 0.80,
                'preco_venda'       => 4.00,
            ],
            [
                'nome'              => 'Fusível 3A 250V',
                'descricao'         => 'Fusível de vidro 3A 250V. Para carregadores e fontes.',
                'sku'               => 'FUS-3A-250V',
                'quantidade'        => 40,
                'quantidade_minima' => 10,
                'preco_custo'       => 0.80,
                'preco_venda'       => 4.00,
            ],
            [
                'nome'              => 'Resistor 10kΩ 1/4W',
                'descricao'         => 'Resistor de filme de carbono 10kΩ 1/4W.',
                'sku'               => 'RES-10K-025W',
                'quantidade'        => 500,
                'quantidade_minima' => 50,
                'preco_custo'       => 0.05,
                'preco_venda'       => 0.50,
            ],
            [
                'nome'              => 'Regulador de Tensão LM7805',
                'descricao'         => 'Regulador de tensão positivo 5V LM7805.',
                'sku'               => 'REG-LM7805',
                'quantidade'        => 40,
                'quantidade_minima' => 10,
                'preco_custo'       => 1.50,
                'preco_venda'       => 6.00,
            ],

            // ── Insumos ────────────────────────────────────────
            [
                'nome'              => 'Pasta Térmica Arctic MX-4',
                'descricao'         => 'Pasta térmica de alta performance para CPUs e GPUs.',
                'sku'               => 'PASTA-ARCTIC-MX4',
                'quantidade'        => 2,
                'quantidade_minima' => 5,
                'preco_custo'       => 15.00,
                'preco_venda'       => 35.00,
            ],
            [
                'nome'              => 'Pasta Térmica Cooler Master',
                'descricao'         => 'Pasta térmica Cooler Master HTK-002 para notebooks.',
                'sku'               => 'PASTA-CM-HTK',
                'quantidade'        => 8,
                'quantidade_minima' => 5,
                'preco_custo'       => 10.00,
                'preco_venda'       => 28.00,
            ],
            [
                'nome'              => 'Álcool Isopropílico 99% 500ml',
                'descricao'         => 'Álcool isopropílico para limpeza de placas e componentes.',
                'sku'               => 'ALC-ISO-500ML',
                'quantidade'        => 3,
                'quantidade_minima' => 2,
                'preco_custo'       => 18.00,
                'preco_venda'       => 40.00,
            ],
            [
                'nome'              => 'Flux para Soldagem Líquido 50ml',
                'descricao'         => 'Flux líquido para facilitar soldagem em SMD e THT.',
                'sku'               => 'FLUX-LIQ-50ML',
                'quantidade'        => 10,
                'quantidade_minima' => 3,
                'preco_custo'       => 12.00,
                'preco_venda'       => 30.00,
            ],
            [
                'nome'              => 'Solda em Fio 60/40 0.8mm 100g',
                'descricao'         => 'Solda estanho/chumbo 60/40 diâmetro 0.8mm.',
                'sku'               => 'SOLDA-6040-08',
                'quantidade'        => 15,
                'quantidade_minima' => 5,
                'preco_custo'       => 22.00,
                'preco_venda'       => 50.00,
            ],
            [
                'nome'              => 'Fita Adesiva Dupla Face 3M',
                'descricao'         => 'Fita dupla face para fixação de telas e componentes.',
                'sku'               => 'FITA-3M-DUP',
                'quantidade'        => 10,
                'quantidade_minima' => 3,
                'preco_custo'       => 8.00,
                'preco_venda'       => 20.00,
            ],
            [
                'nome'              => 'Fita Kapton (Poliimida) 10mm',
                'descricao'         => 'Fita isolante Kapton para proteção durante soldagem.',
                'sku'               => 'FITA-KAPTON-10',
                'quantidade'        => 20,
                'quantidade_minima' => 5,
                'preco_custo'       => 6.00,
                'preco_venda'       => 18.00,
            ],
            [
                'nome'              => 'Malha de Dessoldagem 2.0mm',
                'descricao'         => 'Malha de cobre para remoção de solda.',
                'sku'               => 'MALHA-DES-20',
                'quantidade'        => 25,
                'quantidade_minima' => 5,
                'preco_custo'       => 5.00,
                'preco_venda'       => 15.00,
            ],

            // ── SSD / HD / Memória ─────────────────────────────
            [
                'nome'              => 'SSD SATA 240GB',
                'descricao'         => 'SSD SATA III 240GB. Para upgrade de notebooks e desktops.',
                'sku'               => 'SSD-SATA-240',
                'quantidade'        => 3,
                'quantidade_minima' => 1,
                'preco_custo'       => 120.00,
                'preco_venda'       => 220.00,
            ],
            [
                'nome'              => 'SSD SATA 480GB',
                'descricao'         => 'SSD SATA III 480GB. Alta performance para uso geral.',
                'sku'               => 'SSD-SATA-480',
                'quantidade'        => 2,
                'quantidade_minima' => 1,
                'preco_custo'       => 195.00,
                'preco_venda'       => 340.00,
            ],
            [
                'nome'              => 'SSD M.2 NVMe 256GB',
                'descricao'         => 'SSD M.2 NVMe PCIe 3.0 256GB para notebooks modernos.',
                'sku'               => 'SSD-NVME-256',
                'quantidade'        => 4,
                'quantidade_minima' => 1,
                'preco_custo'       => 160.00,
                'preco_venda'       => 290.00,
            ],
            [
                'nome'              => 'HD SATA 1TB 2.5"',
                'descricao'         => 'HD mecânico SATA 1TB 2.5 polegadas para notebooks.',
                'sku'               => 'HD-SATA-1TB',
                'quantidade'        => 3,
                'quantidade_minima' => 1,
                'preco_custo'       => 180.00,
                'preco_venda'       => 320.00,
            ],
            [
                'nome'              => 'Memória RAM DDR4 8GB 2666MHz',
                'descricao'         => 'Pente de memória RAM DDR4 8GB para notebooks e desktops.',
                'sku'               => 'RAM-DDR4-8GB',
                'quantidade'        => 4,
                'quantidade_minima' => 2,
                'preco_custo'       => 95.00,
                'preco_venda'       => 180.00,
            ],
            [
                'nome'              => 'Memória RAM DDR4 16GB 3200MHz',
                'descricao'         => 'Pente de memória RAM DDR4 16GB para desktops.',
                'sku'               => 'RAM-DDR4-16GB',
                'quantidade'        => 2,
                'quantidade_minima' => 1,
                'preco_custo'       => 160.00,
                'preco_venda'       => 290.00,
            ],
            [
                'nome'              => 'Memória RAM SO-DIMM DDR4 8GB',
                'descricao'         => 'Memória SO-DIMM DDR4 8GB 2666MHz para notebooks.',
                'sku'               => 'RAM-SODIMM-8GB',
                'quantidade'        => 5,
                'quantidade_minima' => 2,
                'preco_custo'       => 98.00,
                'preco_venda'       => 185.00,
            ],

            // ── Acessórios e ferramentas ───────────────────────
            [
                'nome'              => 'Kit Chaves Torx T3-T8',
                'descricao'         => 'Conjunto de chaves Torx T3, T4, T5, T6 e T8 para smartphones.',
                'sku'               => 'KIT-TORX-T3T8',
                'quantidade'        => 8,
                'quantidade_minima' => 2,
                'preco_custo'       => 15.00,
                'preco_venda'       => 40.00,
            ],
            [
                'nome'              => 'Espátula Pry Tool Plástica',
                'descricao'         => 'Espátula plástica para abertura de smartphones sem danos.',
                'sku'               => 'ESP-PRY-PLAS',
                'quantidade'        => 20,
                'quantidade_minima' => 5,
                'preco_custo'       => 3.00,
                'preco_venda'       => 12.00,
            ],
            [
                'nome'              => 'Pinça Anti-estática ESD',
                'descricao'         => 'Pinça de aço inox anti-estática para SMD.',
                'sku'               => 'PINCA-ESD-001',
                'quantidade'        => 10,
                'quantidade_minima' => 3,
                'preco_custo'       => 8.00,
                'preco_venda'       => 22.00,
            ],
            [
                'nome'              => 'Ventosa de Abertura para Tela',
                'descricao'         => 'Ventosa profissional para remoção de telas de smartphones.',
                'sku'               => 'VENT-TELA-001',
                'quantidade'        => 12,
                'quantidade_minima' => 3,
                'preco_custo'       => 5.00,
                'preco_venda'       => 18.00,
            ],
        ];

        foreach ($itens as $item) {
            Estoque::updateOrCreate(
                ['sku' => $item['sku']],
                $item
            );
        }
    }
}