<?php

namespace Database\Seeders;

use App\Models\Fornecedor;
use Illuminate\Database\Seeder;

class FornecedorSeeder extends Seeder
{
    public function run(): void
    {
        $fornecedores = [
            // Originais
            [
                'nome'        => 'TechParts São Paulo',
                'telefone'    => '(11) 3333-4444',
                'email'       => 'vendas@techparts.com.br',
                'contato'     => 'Rafael Cunha',
                'site'        => 'techparts.com.br',
                'observacoes' => 'Entrega em até 2 dias úteis para SP. Frete grátis acima de R$ 300.',
                'ativo'       => true,
            ],
            [
                'nome'        => 'PeçasPhone Distribuidora',
                'telefone'    => '(21) 4444-5555',
                'email'       => 'comercial@pecasphone.com.br',
                'contato'     => 'Camila Duarte',
                'site'        => 'pecasphone.com.br',
                'observacoes' => 'Especializada em peças para celulares. Bom prazo e qualidade.',
                'ativo'       => true,
            ],
            [
                'nome'        => 'Distribuidora Sul Eletrônicos',
                'telefone'    => '(51) 5555-6666',
                'email'       => 'pedidos@distsul.com.br',
                'contato'     => 'Thiago Moreira',
                'site'        => 'distsul.com.br',
                'observacoes' => 'Melhor preço em capacitores e componentes eletrônicos.',
                'ativo'       => true,
            ],
            [
                'nome'        => 'GlobalFix Peças e Acessórios',
                'telefone'    => '(11) 6666-7777',
                'email'       => 'atendimento@globalfix.com.br',
                'contato'     => 'Patricia Nunes',
                'site'        => 'globalfix.com.br',
                'observacoes' => 'Telas e baterias com garantia de 6 meses.',
                'ativo'       => true,
            ],
            [
                'nome'        => 'MercadoPeças Online',
                'telefone'    => null,
                'email'       => 'suporte@mercadopecas.com.br',
                'contato'     => null,
                'site'        => 'mercadopecas.com.br',
                'observacoes' => 'Compras online. Verificar avaliações do vendedor antes de comprar.',
                'ativo'       => true,
            ],
            [
                'nome'        => 'Fornecedor Antigo Ltda',
                'telefone'    => '(11) 2222-3333',
                'email'       => 'contato@fornecedorantigo.com.br',
                'contato'     => 'José Antônio',
                'site'        => null,
                'observacoes' => 'Não trabalha mais com este fornecedor.',
                'ativo'       => false,
            ],

            // Celulares e smartphones
            [
                'nome'        => 'CelMax Distribuidora',
                'telefone'    => '(11) 3210-1234',
                'email'       => 'vendas@celmax.com.br',
                'contato'     => 'Leonardo Dias',
                'site'        => 'celmax.com.br',
                'observacoes' => 'Focada em peças Apple e Samsung. Prazo de 3 dias.',
                'ativo'       => true,
            ],
            [
                'nome'        => 'IPartsStore',
                'telefone'    => '(11) 3210-2345',
                'email'       => 'comercial@ipartsstore.com.br',
                'contato'     => 'Renata Vieira',
                'site'        => 'ipartsstore.com.br',
                'observacoes' => 'Especialista em peças originais para iPhone.',
                'ativo'       => true,
            ],
            [
                'nome'        => 'SmartFix Brasil',
                'telefone'    => '(21) 3210-3456',
                'email'       => 'pedidos@smartfixbrasil.com.br',
                'contato'     => 'Rodrigo Pinto',
                'site'        => 'smartfixbrasil.com.br',
                'observacoes' => 'Grande variedade de telas e conectores.',
                'ativo'       => true,
            ],
            [
                'nome'        => 'PhonePartsRJ',
                'telefone'    => '(21) 3210-4567',
                'email'       => 'vendas@phonepartsrj.com.br',
                'contato'     => 'Amanda Faria',
                'site'        => 'phonepartsrj.com.br',
                'observacoes' => 'Entrega no mesmo dia para clientes do Rio.',
                'ativo'       => true,
            ],
            [
                'nome'        => 'MotoPartes Distribuidora',
                'telefone'    => '(41) 3210-5678',
                'email'       => 'contato@motopartes.com.br',
                'contato'     => 'Sérgio Henrique',
                'site'        => 'motopartes.com.br',
                'observacoes' => 'Especializada em peças Motorola.',
                'ativo'       => true,
            ],
            [
                'nome'        => 'SamsungParts SP',
                'telefone'    => '(11) 3210-6789',
                'email'       => 'comercial@samsungpartssp.com.br',
                'contato'     => 'Flávia Mendes',
                'site'        => 'samsungpartssp.com.br',
                'observacoes' => 'Distribuidora autorizada de peças Samsung.',
                'ativo'       => true,
            ],
            [
                'nome'        => 'XiaomiParts Brasil',
                'telefone'    => '(11) 3210-7890',
                'email'       => 'vendas@xiaomiparts.com.br',
                'contato'     => 'Chen Wei',
                'site'        => 'xiaomiparts.com.br',
                'observacoes' => 'Importadora de peças Xiaomi e Redmi.',
                'ativo'       => true,
            ],

            // Notebooks e computadores
            [
                'nome'        => 'NoteParts Distribuidora',
                'telefone'    => '(11) 3211-1111',
                'email'       => 'vendas@noteparts.com.br',
                'contato'     => 'Daniel Azevedo',
                'site'        => 'noteparts.com.br',
                'observacoes' => 'Peças para notebooks Dell, HP e Lenovo.',
                'ativo'       => true,
            ],
            [
                'nome'        => 'HP Parts Center',
                'telefone'    => '(11) 3211-2222',
                'email'       => 'pedidos@hppartscenter.com.br',
                'contato'     => 'Mônica Braga',
                'site'        => 'hppartscenter.com.br',
                'observacoes' => 'Distribuidora oficial HP para centros de reparo.',
                'ativo'       => true,
            ],
            [
                'nome'        => 'LenovoParts Brasil',
                'telefone'    => '(11) 3211-3333',
                'email'       => 'comercial@lenovoparts.com.br',
                'contato'     => 'Gustavo Yamamura',
                'site'        => 'lenovoparts.com.br',
                'observacoes' => 'Peças originais Lenovo com nota fiscal.',
                'ativo'       => true,
            ],
            [
                'nome'        => 'DellServiceParts',
                'telefone'    => '(11) 3211-4444',
                'email'       => 'atendimento@dellserviceparts.com.br',
                'contato'     => 'Carla Nogueira',
                'site'        => 'dellserviceparts.com.br',
                'observacoes' => 'Peças Dell com garantia estendida de 12 meses.',
                'ativo'       => true,
            ],
            [
                'nome'        => 'MicroFix Computadores',
                'telefone'    => '(31) 3211-5555',
                'email'       => 'vendas@microfix.com.br',
                'contato'     => 'Alexandre Tosta',
                'site'        => 'microfix.com.br',
                'observacoes' => 'Memórias, SSDs e HDDs com bom prazo.',
                'ativo'       => true,
            ],
            [
                'nome'        => 'StorageTech Distribuidora',
                'telefone'    => '(11) 3211-6666',
                'email'       => 'pedidos@storagetech.com.br',
                'contato'     => 'Ivan Marques',
                'site'        => 'storagetech.com.br',
                'observacoes' => 'SSDs, HDDs e pendrives. Melhores preços do mercado.',
                'ativo'       => true,
            ],
            [
                'nome'        => 'RamShop Brasil',
                'telefone'    => '(11) 3211-7777',
                'email'       => 'comercial@ramshop.com.br',
                'contato'     => 'Tatiana Rego',
                'site'        => 'ramshop.com.br',
                'observacoes' => 'Especializada em memórias DDR3, DDR4 e DDR5.',
                'ativo'       => true,
            ],

            // Componentes eletrônicos e insumos
            [
                'nome'        => 'Componentes Sul Ltda',
                'telefone'    => '(51) 3212-1111',
                'email'       => 'vendas@componentessul.com.br',
                'contato'     => 'Nelson Krause',
                'site'        => 'componentessul.com.br',
                'observacoes' => 'Capacitores, resistores e semicondutores a granel.',
                'ativo'       => true,
            ],
            [
                'nome'        => 'ElectroInsumos MG',
                'telefone'    => '(31) 3212-2222',
                'email'       => 'pedidos@electroinsumos.com.br',
                'contato'     => 'Vanderley Souza',
                'site'        => 'electroinsumos.com.br',
                'observacoes' => 'Grande estoque de fusíveis, transistores e diodos.',
                'ativo'       => true,
            ],
            [
                'nome'        => 'CircuitMaster Distribuidora',
                'telefone'    => '(11) 3212-3333',
                'email'       => 'contato@circuitmaster.com.br',
                'contato'     => 'Beatriz Matos',
                'site'        => 'circuitmaster.com.br',
                'observacoes' => 'Componentes SMD e THT com entrega rápida.',
                'ativo'       => true,
            ],
            [
                'nome'        => 'PastaFria Insumos',
                'telefone'    => '(11) 3212-4444',
                'email'       => 'vendas@pastafria.com.br',
                'contato'     => 'Jorge Salazar',
                'site'        => 'pastafria.com.br',
                'observacoes' => 'Especializada em insumos térmicos e de limpeza.',
                'ativo'       => true,
            ],
            [
                'nome'        => 'CleanTech Insumos',
                'telefone'    => '(11) 3212-5555',
                'email'       => 'comercial@cleantech.com.br',
                'contato'     => 'Aline Godoy',
                'site'        => 'cleantech.com.br',
                'observacoes' => 'Álcool isopropílico, escovas e kits de limpeza.',
                'ativo'       => true,
            ],
            [
                'nome'        => 'SolderPro Brasil',
                'telefone'    => '(11) 3212-6666',
                'email'       => 'pedidos@solderpro.com.br',
                'contato'     => 'Mauro Cunha',
                'site'        => 'solderpro.com.br',
                'observacoes' => 'Solda, flux e materiais para bancada técnica.',
                'ativo'       => true,
            ],
            [
                'nome'        => 'AdhesiveFix Distribuidora',
                'telefone'    => '(11) 3212-7777',
                'email'       => 'vendas@adhesivefix.com.br',
                'contato'     => 'Cintia Lara',
                'site'        => 'adhesivefix.com.br',
                'observacoes' => 'Fitas adesivas, cola UV e epóxi para eletrônicos.',
                'ativo'       => true,
            ],

            // Ferramentas e equipamentos
            [
                'nome'        => 'ToolMaster Ferramentas',
                'telefone'    => '(11) 3213-1111',
                'email'       => 'contato@toolmaster.com.br',
                'contato'     => 'Rogério Faria',
                'site'        => 'toolmaster.com.br',
                'observacoes' => 'Chaves torx, spudgers e kits de reparo completos.',
                'ativo'       => true,
            ],
            [
                'nome'        => 'ProTech Equipamentos',
                'telefone'    => '(11) 3213-2222',
                'email'       => 'comercial@protechequip.com.br',
                'contato'     => 'Sandro Bastos',
                'site'        => 'protechequip.com.br',
                'observacoes' => 'Estações de solda, multímetros e fontes de bancada.',
                'ativo'       => true,
            ],
            [
                'nome'        => 'MicroScope Equipamentos',
                'telefone'    => '(11) 3213-3333',
                'email'       => 'vendas@microscope.com.br',
                'contato'     => 'Érica Linhares',
                'site'        => 'microscope.com.br',
                'observacoes' => 'Microscópios para reparo de placas e BGA.',
                'ativo'       => true,
            ],
            [
                'nome'        => 'UltraSonic Cleaning',
                'telefone'    => '(11) 3213-4444',
                'email'       => 'pedidos@ultrasonicbr.com.br',
                'contato'     => 'Maurício Tavares',
                'site'        => 'ultrasonicbr.com.br',
                'observacoes' => 'Lavadoras ultrassônicas e equipamentos de limpeza.',
                'ativo'       => true,
            ],

            // Fornecedores regionais
            [
                'nome'        => 'NordParts Distribuidora',
                'telefone'    => '(81) 3214-1111',
                'email'       => 'vendas@nordparts.com.br',
                'contato'     => 'Edilson Cavalcante',
                'site'        => 'nordparts.com.br',
                'observacoes' => 'Distribuidora do Nordeste. Entrega para PE, BA e CE.',
                'ativo'       => true,
            ],
            [
                'nome'        => 'AmazôniaTech Eletrônicos',
                'telefone'    => '(92) 3214-2222',
                'email'       => 'comercial@amazoniatech.com.br',
                'contato'     => 'Francisca Pantoja',
                'site'        => 'amazoniatech.com.br',
                'observacoes' => 'Distribuidora da Zona Franca de Manaus.',
                'ativo'       => true,
            ],
            [
                'nome'        => 'CentroOeste Peças',
                'telefone'    => '(62) 3214-3333',
                'email'       => 'pedidos@centrooestepecas.com.br',
                'contato'     => 'Divaldo Meireles',
                'site'        => 'centrooestepecas.com.br',
                'observacoes' => 'Atende GO, MT, MS e DF com bom prazo.',
                'ativo'       => true,
            ],

            // Importadoras
            [
                'nome'        => 'ImportFix Electronics',
                'telefone'    => '(11) 3215-1111',
                'email'       => 'vendas@importfix.com.br',
                'contato'     => 'Simone Chow',
                'site'        => 'importfix.com.br',
                'observacoes' => 'Importadora direta da China. Prazos maiores, preços melhores.',
                'ativo'       => true,
            ],
            [
                'nome'        => 'GlobalImport Peças',
                'telefone'    => '(11) 3215-2222',
                'email'       => 'comercial@globalimport.com.br',
                'contato'     => 'Marcos Liu',
                'site'        => 'globalimport.com.br',
                'observacoes' => 'Importação por encomenda. Prazo mínimo de 20 dias.',
                'ativo'       => true,
            ],
            [
                'nome'        => 'ShenzhenParts BR',
                'telefone'    => null,
                'email'       => 'atendimento@shenzhenparts.com.br',
                'contato'     => 'Li Jian',
                'site'        => 'shenzhenparts.com.br',
                'observacoes' => 'Peças genéricas importadas. Qualidade variável.',
                'ativo'       => true,
            ],

            // Fornecedores inativos (para testes)
            [
                'nome'        => 'OldParts Comércio',
                'telefone'    => '(11) 2000-0001',
                'email'       => 'contato@oldparts.com.br',
                'contato'     => 'Alberto Neves',
                'site'        => null,
                'observacoes' => 'Empresa encerrou as atividades.',
                'ativo'       => false,
            ],
            [
                'nome'        => 'Peças & Cia Ltda',
                'telefone'    => '(21) 2000-0002',
                'email'       => 'vendas@pecasecia.com.br',
                'contato'     => 'Raimundo Alencar',
                'site'        => null,
                'observacoes' => 'Muitos problemas com qualidade. Contrato encerrado.',
                'ativo'       => false,
            ],
            [
                'nome'        => 'FastParts Express',
                'telefone'    => '(11) 2000-0003',
                'email'       => 'contato@fastparts.com.br',
                'contato'     => 'Silvana Porto',
                'site'        => 'fastparts.com.br',
                'observacoes' => 'Prazo de entrega nunca cumprido. Descontinuado.',
                'ativo'       => false,
            ],
            [
                'nome'        => 'MegaFix Suprimentos',
                'telefone'    => '(31) 2000-0004',
                'email'       => 'comercial@megafix.com.br',
                'contato'     => 'Antônio Braga',
                'site'        => null,
                'observacoes' => 'Fornecedor encerrou operações em 2024.',
                'ativo'       => false,
            ],
            [
                'nome'        => 'TelaPrima Distribuidora',
                'telefone'    => '(11) 2000-0005',
                'email'       => 'vendas@telaprima.com.br',
                'contato'     => 'Edson Mota',
                'site'        => 'telaprima.com.br',
                'observacoes' => 'Produto com muita reclamação de qualidade.',
                'ativo'       => false,
            ],
        ];

        foreach ($fornecedores as $fornecedor) {
            Fornecedor::updateOrCreate(
                ['email' => $fornecedor['email']],
                $fornecedor
            );
        }
    }
}