<?php

namespace Database\Seeders;

use App\Models\Pedido;
use App\Models\Estoque;
use App\Models\Fornecedor;
use App\Models\User;
use Illuminate\Database\Seeder;

class PedidoSeeder extends Seeder
{
    public function run(): void
    {
        $joao     = User::where('email', 'joao@servicofacil.com')->first();
        $ana      = User::where('email', 'ana@servicofacil.com')->first();
        $carlos   = User::where('email', 'carlos@servicofacil.com')->first();
        $fernanda = User::where('email', 'fernanda@servicofacil.com')->first();
        $lucas    = User::where('email', 'lucas@servicofacil.com')->first();
        $patricia = User::where('email', 'patricia@servicofacil.com')->first();
        $thiago   = User::where('email', 'thiago@servicofacil.com')->first();
        $bianca   = User::where('email', 'bianca@servicofacil.com')->first();

        $techparts  = Fornecedor::where('nome', 'like', 'TechParts%')->first();
        $pecasphone = Fornecedor::where('nome', 'like', 'PeçasPhone%')->first();
        $distsul    = Fornecedor::where('nome', 'like', 'Distribuidora Sul%')->first();
        $globalfix  = Fornecedor::where('nome', 'like', 'GlobalFix%')->first();
        $celmax     = Fornecedor::where('nome', 'like', 'CelMax%')->first();
        $iparts     = Fornecedor::where('nome', 'like', 'IPartsStore%')->first();
        $noteparts  = Fornecedor::where('nome', 'like', 'NoteParts%')->first();
        $solderpro  = Fornecedor::where('nome', 'like', 'SolderPro%')->first();
        $cleantech  = Fornecedor::where('nome', 'like', 'CleanTech%')->first();
        $stotech    = Fornecedor::where('nome', 'like', 'StorageTech%')->first();

        // Estoques
        $telaiph13  = Estoque::where('sku', 'IPH13-TELA-ORI')->first();
        $telaiph14  = Estoque::where('sku', 'IPH14-TELA-ORI')->first();
        $telaiph12  = Estoque::where('sku', 'IPH12-TELA-ORI')->first();
        $telaiph11  = Estoque::where('sku', 'IPH11-TELA-ORI')->first();
        $batsama54  = Estoque::where('sku', 'SAM-A54-BAT')->first();
        $batiph13   = Estoque::where('sku', 'IPH13-BAT')->first();
        $batiph14   = Estoque::where('sku', 'IPH14-BAT')->first();
        $pasta      = Estoque::where('sku', 'PASTA-ARCTIC-MX4')->first();
        $pastacm    = Estoque::where('sku', 'PASTA-CM-HTK')->first();
        $ssd        = Estoque::where('sku', 'SSD-SATA-240')->first();
        $ssd480     = Estoque::where('sku', 'SSD-SATA-480')->first();
        $nvme       = Estoque::where('sku', 'SSD-NVME-256')->first();
        $ram        = Estoque::where('sku', 'RAM-DDR4-8GB')->first();
        $ram16      = Estoque::where('sku', 'RAM-DDR4-16GB')->first();
        $sodimm     = Estoque::where('sku', 'RAM-SODIMM-8GB')->first();
        $tela54     = Estoque::where('sku', 'SAM-A54-TELA')->first();
        $telas23    = Estoque::where('sku', 'SAM-S23-TELA')->first();
        $telag84    = Estoque::where('sku', 'MOT-G84-TELA')->first();
        $alcool     = Estoque::where('sku', 'ALC-ISO-500ML')->first();
        $flux       = Estoque::where('sku', 'FLUX-LIQ-50ML')->first();
        $solda      = Estoque::where('sku', 'SOLDA-6040-08')->first();
        $malha      = Estoque::where('sku', 'MALHA-DES-20')->first();
        $usbc       = Estoque::where('sku', 'CON-USBC-UNI')->first();
        $lightning  = Estoque::where('sku', 'CON-LIGHT-UNI')->first();
        $hd1tb      = Estoque::where('sku', 'HD-SATA-1TB')->first();

        $pedidos = [
            // ── PENDENTES ──────────────────────────────────────
            [
                'estoque_id'       => $telaiph13?->id,
                'fornecedor_id'    => $techparts?->id,
                'solicitado_por'   => $ana?->id,
                'recebido_por'     => null,
                'descricao'        => 'Tela iPhone 13 Original',
                'quantidade'       => 3,
                'preco_unitario'   => null,
                'status'           => 'pendente',
                'numero_pedido'    => null,
                'data_solicitacao' => now()->subDays(2)->toDateString(),
                'data_pedido'      => null,
                'data_previsao'    => null,
                'data_recebimento' => null,
                'observacao'       => 'Urgente! Temos cliente aguardando.',
            ],
            [
                'estoque_id'       => $batsama54?->id,
                'fornecedor_id'    => $pecasphone?->id,
                'solicitado_por'   => $joao?->id,
                'recebido_por'     => null,
                'descricao'        => 'Bateria Samsung Galaxy A54',
                'quantidade'       => 5,
                'preco_unitario'   => null,
                'status'           => 'pendente',
                'numero_pedido'    => null,
                'data_solicitacao' => now()->subDays(1)->toDateString(),
                'data_pedido'      => null,
                'data_previsao'    => null,
                'data_recebimento' => null,
                'observacao'       => null,
            ],
            [
                'estoque_id'       => $telaiph14?->id,
                'fornecedor_id'    => $iparts?->id,
                'solicitado_por'   => $lucas?->id,
                'recebido_por'     => null,
                'descricao'        => 'Tela iPhone 14 Original',
                'quantidade'       => 2,
                'preco_unitario'   => null,
                'status'           => 'pendente',
                'numero_pedido'    => null,
                'data_solicitacao' => now()->subDays(1)->toDateString(),
                'data_pedido'      => null,
                'data_previsao'    => null,
                'data_recebimento' => null,
                'observacao'       => 'Verificar disponibilidade com fornecedor.',
            ],
            [
                'estoque_id'       => $alcool?->id,
                'fornecedor_id'    => $cleantech?->id,
                'solicitado_por'   => $bianca?->id,
                'recebido_por'     => null,
                'descricao'        => 'Álcool Isopropílico 99% 500ml',
                'quantidade'       => 10,
                'preco_unitario'   => null,
                'status'           => 'pendente',
                'numero_pedido'    => null,
                'data_solicitacao' => now()->toDateString(),
                'data_pedido'      => null,
                'data_previsao'    => null,
                'data_recebimento' => null,
                'observacao'       => 'Estoque quase zerado.',
            ],
            [
                'estoque_id'       => $batiph13?->id,
                'fornecedor_id'    => $techparts?->id,
                'solicitado_por'   => $fernanda?->id,
                'recebido_por'     => null,
                'descricao'        => 'Bateria iPhone 13',
                'quantidade'       => 5,
                'preco_unitario'   => null,
                'status'           => 'pendente',
                'numero_pedido'    => null,
                'data_solicitacao' => now()->subDays(3)->toDateString(),
                'data_pedido'      => null,
                'data_previsao'    => null,
                'data_recebimento' => null,
                'observacao'       => null,
            ],
            [
                'estoque_id'       => $usbc?->id,
                'fornecedor_id'    => $celmax?->id,
                'solicitado_por'   => $thiago?->id,
                'recebido_por'     => null,
                'descricao'        => 'Conector USB-C Universal',
                'quantidade'       => 20,
                'preco_unitario'   => null,
                'status'           => 'pendente',
                'numero_pedido'    => null,
                'data_solicitacao' => now()->subDays(2)->toDateString(),
                'data_pedido'      => null,
                'data_previsao'    => null,
                'data_recebimento' => null,
                'observacao'       => null,
            ],

            // ── PEDIDO (enviados ao fornecedor) ────────────────
            [
                'estoque_id'       => $pasta?->id,
                'fornecedor_id'    => $distsul?->id,
                'solicitado_por'   => $carlos?->id,
                'recebido_por'     => null,
                'descricao'        => 'Pasta Térmica Arctic MX-4',
                'quantidade'       => 10,
                'preco_unitario'   => null,
                'status'           => 'pedido',
                'numero_pedido'    => 'PED-2026-001',
                'data_solicitacao' => now()->subDays(5)->toDateString(),
                'data_pedido'      => now()->subDays(3)->toDateString(),
                'data_previsao'    => now()->addDays(2)->toDateString(),
                'data_recebimento' => null,
                'observacao'       => 'Pedido feito por e-mail. Aguardando confirmação.',
            ],
            [
                'estoque_id'       => $ssd?->id,
                'fornecedor_id'    => $techparts?->id,
                'solicitado_por'   => $fernanda?->id,
                'recebido_por'     => null,
                'descricao'        => 'SSD SATA 240GB',
                'quantidade'       => 2,
                'preco_unitario'   => null,
                'status'           => 'pedido',
                'numero_pedido'    => 'PED-2026-002',
                'data_solicitacao' => now()->subDays(7)->toDateString(),
                'data_pedido'      => now()->subDays(6)->toDateString(),
                'data_previsao'    => now()->subDays(1)->toDateString(),
                'data_recebimento' => null,
                'observacao'       => 'Previsão já passou. Cobrar o fornecedor.',
            ],
            [
                'estoque_id'       => $telas23?->id,
                'fornecedor_id'    => $pecasphone?->id,
                'solicitado_por'   => $lucas?->id,
                'recebido_por'     => null,
                'descricao'        => 'Tela Samsung Galaxy S23',
                'quantidade'       => 2,
                'preco_unitario'   => null,
                'status'           => 'pedido',
                'numero_pedido'    => 'PED-2026-005',
                'data_solicitacao' => now()->subDays(6)->toDateString(),
                'data_pedido'      => now()->subDays(4)->toDateString(),
                'data_previsao'    => now()->addDays(3)->toDateString(),
                'data_recebimento' => null,
                'observacao'       => 'Confirmar número de série.',
            ],
            [
                'estoque_id'       => $nvme?->id,
                'fornecedor_id'    => $stotech?->id,
                'solicitado_por'   => $carlos?->id,
                'recebido_por'     => null,
                'descricao'        => 'SSD M.2 NVMe 256GB',
                'quantidade'       => 3,
                'preco_unitario'   => null,
                'status'           => 'pedido',
                'numero_pedido'    => 'PED-2026-006',
                'data_solicitacao' => now()->subDays(8)->toDateString(),
                'data_pedido'      => now()->subDays(7)->toDateString(),
                'data_previsao'    => now()->addDays(1)->toDateString(),
                'data_recebimento' => null,
                'observacao'       => null,
            ],
            [
                'estoque_id'       => $sodimm?->id,
                'fornecedor_id'    => $noteparts?->id,
                'solicitado_por'   => $ana?->id,
                'recebido_por'     => null,
                'descricao'        => 'Memória SO-DIMM DDR4 8GB',
                'quantidade'       => 4,
                'preco_unitario'   => null,
                'status'           => 'pedido',
                'numero_pedido'    => 'PED-2026-007',
                'data_solicitacao' => now()->subDays(4)->toDateString(),
                'data_pedido'      => now()->subDays(3)->toDateString(),
                'data_previsao'    => now()->addDays(4)->toDateString(),
                'data_recebimento' => null,
                'observacao'       => 'Compatível com Dell e HP.',
            ],
            [
                'estoque_id'       => $flux?->id,
                'fornecedor_id'    => $solderpro?->id,
                'solicitado_por'   => $thiago?->id,
                'recebido_por'     => null,
                'descricao'        => 'Flux para Soldagem Líquido 50ml',
                'quantidade'       => 5,
                'preco_unitario'   => null,
                'status'           => 'pedido',
                'numero_pedido'    => 'PED-2026-008',
                'data_solicitacao' => now()->subDays(9)->toDateString(),
                'data_pedido'      => now()->subDays(8)->toDateString(),
                'data_previsao'    => now()->subDays(2)->toDateString(),
                'data_recebimento' => null,
                'observacao'       => 'Atraso de 2 dias. Fornecedor avisou.',
            ],
            [
                'estoque_id'       => $lightning?->id,
                'fornecedor_id'    => $iparts?->id,
                'solicitado_por'   => $joao?->id,
                'recebido_por'     => null,
                'descricao'        => 'Conector Lightning (iPhone)',
                'quantidade'       => 10,
                'preco_unitario'   => null,
                'status'           => 'pedido',
                'numero_pedido'    => 'PED-2026-009',
                'data_solicitacao' => now()->subDays(5)->toDateString(),
                'data_pedido'      => now()->subDays(4)->toDateString(),
                'data_previsao'    => now()->addDays(2)->toDateString(),
                'data_recebimento' => null,
                'observacao'       => null,
            ],
            [
                'estoque_id'       => $ssd480?->id,
                'fornecedor_id'    => $stotech?->id,
                'solicitado_por'   => $patricia?->id,
                'recebido_por'     => null,
                'descricao'        => 'SSD SATA 480GB',
                'quantidade'       => 2,
                'preco_unitario'   => null,
                'status'           => 'pedido',
                'numero_pedido'    => 'PED-2026-010',
                'data_solicitacao' => now()->subDays(10)->toDateString(),
                'data_pedido'      => now()->subDays(9)->toDateString(),
                'data_previsao'    => now()->addDays(1)->toDateString(),
                'data_recebimento' => null,
                'observacao'       => null,
            ],
            [
                'estoque_id'       => $solda?->id,
                'fornecedor_id'    => $solderpro?->id,
                'solicitado_por'   => $bianca?->id,
                'recebido_por'     => null,
                'descricao'        => 'Solda em Fio 60/40 0.8mm 100g',
                'quantidade'       => 8,
                'preco_unitario'   => null,
                'status'           => 'pedido',
                'numero_pedido'    => 'PED-2026-011',
                'data_solicitacao' => now()->subDays(6)->toDateString(),
                'data_pedido'      => now()->subDays(5)->toDateString(),
                'data_previsao'    => now()->addDays(3)->toDateString(),
                'data_recebimento' => null,
                'observacao'       => null,
            ],
            [
                'estoque_id'       => $telaiph12?->id,
                'fornecedor_id'    => $iparts?->id,
                'solicitado_por'   => $ana?->id,
                'recebido_por'     => null,
                'descricao'        => 'Tela iPhone 12 Original',
                'quantidade'       => 3,
                'preco_unitario'   => null,
                'status'           => 'pedido',
                'numero_pedido'    => 'PED-2026-012',
                'data_solicitacao' => now()->subDays(7)->toDateString(),
                'data_pedido'      => now()->subDays(6)->toDateString(),
                'data_previsao'    => now()->addDays(2)->toDateString(),
                'data_recebimento' => null,
                'observacao'       => null,
            ],

            // ── RECEBIDOS ──────────────────────────────────────
            [
                'estoque_id'       => $tela54?->id,
                'fornecedor_id'    => $pecasphone?->id,
                'solicitado_por'   => $ana?->id,
                'recebido_por'     => $ana?->id,
                'descricao'        => 'Tela Samsung Galaxy A54',
                'quantidade'       => 5,
                'preco_unitario'   => 120.00,
                'status'           => 'recebido',
                'numero_pedido'    => 'PED-2026-003',
                'data_solicitacao' => now()->subDays(15)->toDateString(),
                'data_pedido'      => now()->subDays(13)->toDateString(),
                'data_previsao'    => now()->subDays(8)->toDateString(),
                'data_recebimento' => now()->subDays(7)->toDateString(),
                'observacao'       => 'Recebido com nota fiscal.',
            ],
            [
                'estoque_id'       => $ram?->id,
                'fornecedor_id'    => $techparts?->id,
                'solicitado_por'   => $joao?->id,
                'recebido_por'     => $joao?->id,
                'descricao'        => 'Memória RAM DDR4 8GB',
                'quantidade'       => 4,
                'preco_unitario'   => 95.00,
                'status'           => 'recebido',
                'numero_pedido'    => 'PED-2026-004',
                'data_solicitacao' => now()->subDays(20)->toDateString(),
                'data_pedido'      => now()->subDays(18)->toDateString(),
                'data_previsao'    => now()->subDays(12)->toDateString(),
                'data_recebimento' => now()->subDays(10)->toDateString(),
                'observacao'       => null,
            ],
            [
                'estoque_id'       => $telag84?->id,
                'fornecedor_id'    => $globalfix?->id,
                'solicitado_por'   => $carlos?->id,
                'recebido_por'     => $carlos?->id,
                'descricao'        => 'Tela Motorola Moto G84',
                'quantidade'       => 3,
                'preco_unitario'   => 95.00,
                'status'           => 'recebido',
                'numero_pedido'    => 'PED-2026-013',
                'data_solicitacao' => now()->subDays(25)->toDateString(),
                'data_pedido'      => now()->subDays(23)->toDateString(),
                'data_previsao'    => now()->subDays(16)->toDateString(),
                'data_recebimento' => now()->subDays(14)->toDateString(),
                'observacao'       => 'Tudo OK. Itens em perfeito estado.',
            ],
            [
                'estoque_id'       => $pastacm?->id,
                'fornecedor_id'    => $distsul?->id,
                'solicitado_por'   => $lucas?->id,
                'recebido_por'     => $lucas?->id,
                'descricao'        => 'Pasta Térmica Cooler Master',
                'quantidade'       => 6,
                'preco_unitario'   => 10.00,
                'status'           => 'recebido',
                'numero_pedido'    => 'PED-2026-014',
                'data_solicitacao' => now()->subDays(18)->toDateString(),
                'data_pedido'      => now()->subDays(16)->toDateString(),
                'data_previsao'    => now()->subDays(10)->toDateString(),
                'data_recebimento' => now()->subDays(9)->toDateString(),
                'observacao'       => null,
            ],
            [
                'estoque_id'       => $malha?->id,
                'fornecedor_id'    => $solderpro?->id,
                'solicitado_por'   => $bianca?->id,
                'recebido_por'     => $bianca?->id,
                'descricao'        => 'Malha de Dessoldagem 2.0mm',
                'quantidade'       => 10,
                'preco_unitario'   => 5.00,
                'status'           => 'recebido',
                'numero_pedido'    => 'PED-2026-015',
                'data_solicitacao' => now()->subDays(22)->toDateString(),
                'data_pedido'      => now()->subDays(20)->toDateString(),
                'data_previsao'    => now()->subDays(14)->toDateString(),
                'data_recebimento' => now()->subDays(13)->toDateString(),
                'observacao'       => null,
            ],
            [
                'estoque_id'       => $hd1tb?->id,
                'fornecedor_id'    => $stotech?->id,
                'solicitado_por'   => $fernanda?->id,
                'recebido_por'     => $fernanda?->id,
                'descricao'        => 'HD SATA 1TB 2.5"',
                'quantidade'       => 2,
                'preco_unitario'   => 180.00,
                'status'           => 'recebido',
                'numero_pedido'    => 'PED-2026-016',
                'data_solicitacao' => now()->subDays(30)->toDateString(),
                'data_pedido'      => now()->subDays(28)->toDateString(),
                'data_previsao'    => now()->subDays(20)->toDateString(),
                'data_recebimento' => now()->subDays(19)->toDateString(),
                'observacao'       => 'Nota fiscal conferida.',
            ],
            [
                'estoque_id'       => $telaiph11?->id,
                'fornecedor_id'    => $iparts?->id,
                'solicitado_por'   => $joao?->id,
                'recebido_por'     => $joao?->id,
                'descricao'        => 'Tela iPhone 11 Original',
                'quantidade'       => 4,
                'preco_unitario'   => 130.00,
                'status'           => 'recebido',
                'numero_pedido'    => 'PED-2026-017',
                'data_solicitacao' => now()->subDays(35)->toDateString(),
                'data_pedido'      => now()->subDays(33)->toDateString(),
                'data_previsao'    => now()->subDays(25)->toDateString(),
                'data_recebimento' => now()->subDays(24)->toDateString(),
                'observacao'       => null,
            ],
            [
                'estoque_id'       => $batiph14?->id,
                'fornecedor_id'    => $techparts?->id,
                'solicitado_por'   => $patricia?->id,
                'recebido_por'     => $patricia?->id,
                'descricao'        => 'Bateria iPhone 14',
                'quantidade'       => 3,
                'preco_unitario'   => 100.00,
                'status'           => 'recebido',
                'numero_pedido'    => 'PED-2026-018',
                'data_solicitacao' => now()->subDays(28)->toDateString(),
                'data_pedido'      => now()->subDays(26)->toDateString(),
                'data_previsao'    => now()->subDays(18)->toDateString(),
                'data_recebimento' => now()->subDays(17)->toDateString(),
                'observacao'       => null,
            ],
            [
                'estoque_id'       => $ram16?->id,
                'fornecedor_id'    => $stotech?->id,
                'solicitado_por'   => $carlos?->id,
                'recebido_por'     => $carlos?->id,
                'descricao'        => 'Memória RAM DDR4 16GB',
                'quantidade'       => 2,
                'preco_unitario'   => 160.00,
                'status'           => 'recebido',
                'numero_pedido'    => 'PED-2026-019',
                'data_solicitacao' => now()->subDays(40)->toDateString(),
                'data_pedido'      => now()->subDays(38)->toDateString(),
                'data_previsao'    => now()->subDays(30)->toDateString(),
                'data_recebimento' => now()->subDays(29)->toDateString(),
                'observacao'       => null,
            ],
            [
                'estoque_id'       => $usbc?->id,
                'fornecedor_id'    => $celmax?->id,
                'solicitado_por'   => $thiago?->id,
                'recebido_por'     => $thiago?->id,
                'descricao'        => 'Conector USB-C Universal',
                'quantidade'       => 15,
                'preco_unitario'   => 12.00,
                'status'           => 'recebido',
                'numero_pedido'    => 'PED-2026-020',
                'data_solicitacao' => now()->subDays(45)->toDateString(),
                'data_pedido'      => now()->subDays(43)->toDateString(),
                'data_previsao'    => now()->subDays(35)->toDateString(),
                'data_recebimento' => now()->subDays(34)->toDateString(),
                'observacao'       => 'Lote com 15 unidades sem defeitos.',
            ],
            [
                'estoque_id'       => $alcool?->id,
                'fornecedor_id'    => $cleantech?->id,
                'solicitado_por'   => $ana?->id,
                'recebido_por'     => $ana?->id,
                'descricao'        => 'Álcool Isopropílico 99% 500ml',
                'quantidade'       => 5,
                'preco_unitario'   => 18.00,
                'status'           => 'recebido',
                'numero_pedido'    => 'PED-2026-021',
                'data_solicitacao' => now()->subDays(50)->toDateString(),
                'data_pedido'      => now()->subDays(48)->toDateString(),
                'data_previsao'    => now()->subDays(40)->toDateString(),
                'data_recebimento' => now()->subDays(39)->toDateString(),
                'observacao'       => null,
            ],
            [
                'estoque_id'       => $lightning?->id,
                'fornecedor_id'    => $iparts?->id,
                'solicitado_por'   => $fernanda?->id,
                'recebido_por'     => $fernanda?->id,
                'descricao'        => 'Conector Lightning (iPhone)',
                'quantidade'       => 8,
                'preco_unitario'   => 18.00,
                'status'           => 'recebido',
                'numero_pedido'    => 'PED-2026-022',
                'data_solicitacao' => now()->subDays(55)->toDateString(),
                'data_pedido'      => now()->subDays(53)->toDateString(),
                'data_previsao'    => now()->subDays(45)->toDateString(),
                'data_recebimento' => now()->subDays(44)->toDateString(),
                'observacao'       => null,
            ],

            // ── CANCELADOS ─────────────────────────────────────
            [
                'estoque_id'       => null,
                'fornecedor_id'    => $distsul?->id,
                'solicitado_por'   => $fernanda?->id,
                'recebido_por'     => null,
                'descricao'        => 'Placa mãe Notebook Positivo',
                'quantidade'       => 1,
                'preco_unitario'   => null,
                'status'           => 'cancelado',
                'numero_pedido'    => null,
                'data_solicitacao' => now()->subDays(10)->toDateString(),
                'data_pedido'      => null,
                'data_previsao'    => null,
                'data_recebimento' => null,
                'observacao'       => 'Cliente desistiu do reparo. Pedido cancelado.',
            ],
            [
                'estoque_id'       => null,
                'fornecedor_id'    => $pecasphone?->id,
                'solicitado_por'   => $joao?->id,
                'recebido_por'     => null,
                'descricao'        => 'Tela OLED Xiaomi 12 Pro',
                'quantidade'       => 1,
                'preco_unitario'   => null,
                'status'           => 'cancelado',
                'numero_pedido'    => null,
                'data_solicitacao' => now()->subDays(14)->toDateString(),
                'data_pedido'      => null,
                'data_previsao'    => null,
                'data_recebimento' => null,
                'observacao'       => 'Fornecedor não tem em estoque. Cancelado.',
            ],
            [
                'estoque_id'       => $ssd?->id,
                'fornecedor_id'    => $stotech?->id,
                'solicitado_por'   => $carlos?->id,
                'recebido_por'     => null,
                'descricao'        => 'SSD SATA 240GB',
                'quantidade'       => 5,
                'preco_unitario'   => null,
                'status'           => 'cancelado',
                'numero_pedido'    => 'PED-2026-023',
                'data_solicitacao' => now()->subDays(20)->toDateString(),
                'data_pedido'      => now()->subDays(19)->toDateString(),
                'data_previsao'    => null,
                'data_recebimento' => null,
                'observacao'       => 'Preço fora do esperado. Pedido cancelado.',
            ],
            [
                'estoque_id'       => null,
                'fornecedor_id'    => $globalfix?->id,
                'solicitado_por'   => $ana?->id,
                'recebido_por'     => null,
                'descricao'        => 'Câmera traseira Samsung Galaxy A34',
                'quantidade'       => 2,
                'preco_unitario'   => null,
                'status'           => 'cancelado',
                'numero_pedido'    => null,
                'data_solicitacao' => now()->subDays(12)->toDateString(),
                'data_pedido'      => null,
                'data_previsao'    => null,
                'data_recebimento' => null,
                'observacao'       => 'Peça descontinuada pelo fornecedor.',
            ],
            [
                'estoque_id'       => null,
                'fornecedor_id'    => $techparts?->id,
                'solicitado_por'   => $thiago?->id,
                'recebido_por'     => null,
                'descricao'        => 'Fonte interna Notebook HP 65W',
                'quantidade'       => 1,
                'preco_unitario'   => null,
                'status'           => 'cancelado',
                'numero_pedido'    => null,
                'data_solicitacao' => now()->subDays(8)->toDateString(),
                'data_pedido'      => null,
                'data_previsao'    => null,
                'data_recebimento' => null,
                'observacao'       => 'Cliente optou por não consertar.',
            ],
            [
                'estoque_id'       => $batiph13?->id,
                'fornecedor_id'    => $iparts?->id,
                'solicitado_por'   => $bianca?->id,
                'recebido_por'     => null,
                'descricao'        => 'Bateria iPhone 13 (duplicata)',
                'quantidade'       => 3,
                'preco_unitario'   => null,
                'status'           => 'cancelado',
                'numero_pedido'    => 'PED-2026-024',
                'data_solicitacao' => now()->subDays(11)->toDateString(),
                'data_pedido'      => now()->subDays(10)->toDateString(),
                'data_previsao'    => null,
                'data_recebimento' => null,
                'observacao'       => 'Pedido duplicado. Cancelado manualmente.',
            ],
        ];

        foreach ($pedidos as $pedido) {
            Pedido::create($pedido);
        }
    }
}